/* global React, ReactDOM, Icon, Gate, Rail, Ribbon, Composer, UserMessage, OracleMessage, ArchiveCard, PERSONAS, SEED, TOOLS, Flourish, TweaksPanel, TweakSection, TweakRadio, TweakToggle, TweakColor, TweakSlider, useTweaks */
const { useState, useEffect, useRef, useMemo, useCallback } = React;

// ───────────────────────────────────────────────────────────────
// Scripted reply engine — picks a plausible response based on
// keywords, with a streaming animation.
// ───────────────────────────────────────────────────────────────

function pickReply(userText, persona) {
  const t = userText.toLowerCase();

  // Search / look up
  if (/(search|look up|find|recent|2026|review|reviewer|web|google|news)/.test(t)) {
    return {
      persona: 'cartographer',
      toolCalls: [{
        id: 'gen-' + Date.now(),
        tool: 'lens',
        status: 'pending',
        args: { query: userText.slice(0, 60), recency: 'last 6 months', limit: 5 },
        result: {
          summary: 'Five new posts, all from the last quarter.',
          sources: [
            { n: 1, title: 'A working draughtsman replies', domain: 'inkforge.review', date: '2026-04-30' },
            { n: 2, title: 'The case for slower tools', domain: 'desk-and-quill.com', date: '2026-04-18' },
            { n: 3, title: 'On the question, plainly', domain: 'cartographer.notes', date: '2026-03-22' },
            { n: 4, title: 'A field guide', domain: 'paperandink.studio', date: '2026-03-04' },
            { n: 5, title: 'Counter-argument from the other side of the bridge', domain: 'twocities.review', date: '2026-02-12' },
          ],
        },
      }],
      text:
`Five new posts since the last fortnight. The short of it:

- **The plain answer is the right one.** Three of the five take the same position. The other two are dissenting, mostly on price.
- **Recency matters more than I expected.** The strongest argument is in the *newest* post — published two days ago.

If you'd like a deeper survey, the Cartographer can chart a longer route. Otherwise this is enough to choose by.`,
    };
  }

  // Code / table / compute
  if (/(table|chart|render|compute|calculate|code|csv|python|run|graph)/.test(t)) {
    return {
      persona: 'tinker',
      toolCalls: [{
        id: 'gen-' + Date.now(),
        tool: 'loom',
        status: 'pending',
        args: { language: 'python', script: '# generated by the Tinker\nprint(do_the_thing())' },
        result: {
          summary: 'Spun in 0.4s · returned cleanly',
          markdown:
`| Variable | Value | Note            |
|----------|-------|-----------------|
| α        | 12    | within range    |
| β        | 0.84  | acceptable      |
| γ        | 7     | flagged for review |`,
        },
      }],
      text: `Done. The output is in the loom card above — copy it or call for a different cut.\n\nA caveat: the *γ* row is flagged. The Tinker isn't sure whether that's a number you wanted or a number you got. Worth checking.`,
    };
  }

  // Archive / past / old / yesterday
  if (/(remember|yesterday|past|earlier|before|last (week|month)|archive|scroll)/.test(t)) {
    return {
      persona: 'loremaster',
      toolCalls: [{
        id: 'gen-' + Date.now(),
        tool: 'archive',
        status: 'pending',
        args: { window: 'last 30 days', match: userText.slice(0, 40) },
        result: {
          summary: 'Two matching scrolls retrieved.',
          text: '',
          sources: [
            { n: 1, title: 'Scroll: On the bookshelf measurements', domain: '6 days ago · 6 turns' },
            { n: 2, title: 'Scroll: Drafting the workshop schedule', domain: '2 weeks ago · 14 turns' },
          ],
        },
      }],
      text:
`Two scrolls match. The relevant lines, in plain language:

> From the bookshelf scroll: *five shelves, base 360 mm, then 320 / 280 / 240 / 240.*
> From the workshop scroll: *finishing stays before joinery, against the Oracle's advice.*

Which one would you like unrolled in full?`,
    };
  }

  // Greeting / short
  if (/^(hi|hello|hey|greetings|good (morning|day|evening))[\s.!?]*$/i.test(t)) {
    return {
      persona,
      text: `A good evening to you. The lantern is lit; the kettle is on. What are you working on?`,
    };
  }

  // Help / what can you do
  if (/(what can you do|help|commands|tools)/.test(t)) {
    return {
      persona,
      text:
`I keep a single, long conversation with you — the Archivist condenses the older parts so we have room. I can call on three instruments when they help:

- **The Cartographer's Lens** — search the open web for things newer than the Keep's own books.
- **The Archive** — fetch lines from earlier in our conversation, or from the scrolls you've stored here.
- **The Loom** — spin and run code when the answer wants a number, a table, or a script.

I will only reach for a tool if it earns its place. Otherwise I'll just speak plainly.

Try me with anything — the weather of an argument, a piece of writing to read, a measurement you can't quite pin down.`,
    };
  }

  // Default — plain reply
  const replies = {
    oracle: `That's a fair question. The honest answer is that there are three ways to read it, and the right one depends on what you actually want at the end.

The first reading takes the words at face value — useful but uninteresting. The second assumes a hidden constraint and works backwards from it; this is where most people end up. The third — which I prefer — sets the question aside and asks a different one: *what are you trying to build?* Tell me that and I can give you a real answer instead of a clever one.

What's the project beneath this?`,

    cartographer: `Before I chart, I want to be sure of the territory. I read the question two ways, and my answer differs by which one you mean.

If you mean *the documented practice* — what the better reviewers and primary sources say in 2026 — I can pull a survey in under a minute.
If you mean *what works in your hand* — the question is shorter and the answer is messier; mostly it depends on the paper you have on the desk right now.

Which would you like?`,

    loremaster: `An older question than it looks. The same conversation appears in print at least three times — once in a 1923 journal, once in a 1968 manual, and most recently in a 2019 thread that quotes both without crediting either.

The 1923 piece has the better answer. It is shorter and the writer was using the tool every day. The 1968 manual is more thorough but written by someone who had stopped using it.

If you'd like, I can pull the relevant page.`,

    tinker: `Let me state the question as I'd write it for the loom, then answer it twice — once in plain language, once in pseudocode.

**Plain:** the trade-off is between the thing being *easy to change* and the thing being *easy to read*. You usually only get one. Pick the one the next person opening this file will need.

\`\`\`
fn decide(use_case):
  if reads_per_change > 5: prefer readability
  else:                    prefer mutability
\`\`\`

Tell me the ratio and I'll give you a number instead of a rule.`,
  };

  return { persona, text: replies[persona] || replies.oracle };
}

// ───────────────────────────────────────────────────────────────
// LocalStorage helpers
// ───────────────────────────────────────────────────────────────

const LS_KEY = 'oracle-keep::session::v1';

function loadSession() {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch { return null; }
}
function saveSession(state) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(state)); } catch {}
}

// ───────────────────────────────────────────────────────────────
// Tweak defaults (persisted on disk via host)
// ───────────────────────────────────────────────────────────────

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "accent": "#C56A1F",
  "density": 4,
  "ribbon": true,
  "proseWidth": 760,
  "fontSize": 16,
  "lanternFlicker": true,
  "showResume": true,
  "compactionThreshold": 12
}/*EDITMODE-END*/;

// ───────────────────────────────────────────────────────────────

function App() {
  // Tweaks
  const [tweaks, setTweaks] = useTweaks(TWEAK_DEFAULTS);

  // Auth gate
  const [showGate, setShowGate] = useState(true);

  // Conversation state
  const saved = useRef(loadSession()).current;
  const [items, setItems] = useState(() => saved?.items || SEED);
  const [persona, setPersona] = useState(() => saved?.persona || 'oracle');
  const [theme, setTheme] = useState(() => saved?.theme || 'light');
  const [railCollapsed, setRailCollapsed] = useState(false);
  const [personaMenuOpen, setPersonaMenuOpen] = useState(false);
  const [activeTools, setActiveTools] = useState({ lens: true, archive: true, loom: true });
  const [streamingIdx, setStreamingIdx] = useState(-1);
  const [pendingText, setPendingText] = useState('');
  const [pending, setPending] = useState(false);
  const [showResume, setShowResume] = useState(!!saved && tweaks.showResume);
  const [activeArchive, setActiveArchive] = useState(null);
  const [suggestion, setSuggestion] = useState('');

  const convoRef = useRef(null);

  // Persist
  useEffect(() => {
    saveSession({ items, persona, theme });
  }, [items, persona, theme]);

  // Theme on root
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  // Accent live update
  useEffect(() => {
    if (tweaks.accent) {
      document.documentElement.style.setProperty('--ember-500', tweaks.accent);
    }
  }, [tweaks.accent]);

  // Auto-scroll to bottom when new items appear
  useEffect(() => {
    if (!convoRef.current) return;
    convoRef.current.scrollTop = convoRef.current.scrollHeight;
  }, [items.length]);
  useEffect(() => {
    if (!convoRef.current || streamingIdx < 0) return;
    convoRef.current.scrollTop = convoRef.current.scrollHeight;
  }, [pendingText, streamingIdx]);

  const archives = useMemo(() => items.filter(x => x.kind === 'archive'), [items]);

  // ── Submit a user message and generate a reply ───────────────
  const sendMessage = useCallback((text) => {
    if (pending) return;
    const now = 'just now';
    const userItem = { kind: 'user', id: 'u-' + Date.now(), text, timeAgo: now };
    setPending(true);
    setItems(prev => [...prev, userItem]);

    // Generate
    const reply = pickReply(text, persona);
    const replyItem = {
      kind: 'oracle',
      id: 'o-' + Date.now(),
      persona: reply.persona,
      timeAgo: now,
      text: '',                              // streamed in
      toolCalls: reply.toolCalls ? reply.toolCalls.map(tc => ({ ...tc, status: 'pending' })) : undefined,
    };

    // Add reply placeholder shortly after
    setTimeout(() => {
      setItems(prev => {
        const next = [...prev, replyItem];
        setStreamingIdx(next.length - 1);
        return next;
      });
      runReply(reply, replyItem.id);
    }, 350);
  }, [pending, persona]);

  // ── Run a reply: tool delays, then stream text ───────────────
  const runReply = useCallback((reply, replyId) => {
    const finishToolsThenStream = () => {
      // Mark tools done
      if (reply.toolCalls?.length) {
        setItems(prev => prev.map(it => {
          if (it.id !== replyId) return it;
          return { ...it, toolCalls: it.toolCalls.map(tc => {
            const orig = reply.toolCalls.find(o => o.id === tc.id);
            return { ...tc, status: 'done', result: orig?.result };
          }) };
        }));
      }
      // Stream text
      streamText(reply.text || '', (acc, done) => {
        setPendingText(acc);
        if (done) {
          setItems(prev => prev.map(it => it.id === replyId ? { ...it, text: reply.text } : it));
          setStreamingIdx(-1);
          setPendingText('');
          setPending(false);
        }
      });
    };

    if (reply.toolCalls?.length) {
      // pretend the tool is running
      setTimeout(finishToolsThenStream, 1100);
    } else {
      setTimeout(finishToolsThenStream, 250);
    }
  }, []);

  // Streaming helper — emits accumulated text every ~30ms
  const streamText = useCallback((full, cb) => {
    if (!full) { cb('', true); return; }
    const tokens = full.split(/(\s+)/); // keep whitespace
    let i = 0;
    let acc = '';
    const step = () => {
      const chunk = tokens.slice(i, i + 2).join('');
      acc += chunk;
      i += 2;
      cb(acc, false);
      if (i < tokens.length) {
        setTimeout(step, 18 + Math.random() * 20);
      } else {
        cb(full, true);
      }
    };
    step();
  }, []);

  // Toggle tools
  const onToggleTool = (k) => setActiveTools(prev => ({ ...prev, [k]: !prev[k] }));

  // Toggle theme
  const toggleTheme = () => setTheme(theme === 'dark' ? 'light' : 'dark');

  // Persona selection
  const selectPersona = (id) => { setPersona(id); setPersonaMenuOpen(false); };

  // Jump to item in convo
  const jumpTo = (idx) => {
    const el = document.querySelector(`[data-item-idx="${idx}"]`);
    if (el && convoRef.current) {
      const top = el.getBoundingClientRect().top - convoRef.current.getBoundingClientRect().top + convoRef.current.scrollTop - 24;
      convoRef.current.scrollTo({ top, behavior: 'smooth' });
    }
  };

  // Reset / "start a new keep" (for demo)
  const newSession = () => {
    if (!confirm('Start a fresh session? The current archive will be remembered.')) return;
    setItems(SEED);
    setShowResume(false);
  };

  // Suggestion clicks
  const onSuggestion = (s) => { setSuggestion(s); setTimeout(() => setSuggestion(''), 50); };

  // Current persona obj
  const personaObj = PERSONAS.find(p => p.id === persona) || PERSONAS[0];

  // Density styling
  const gap = [40, 36, 34, 32, 30, 28, 26, 22, 18, 14][Math.max(0, Math.min(9, tweaks.density - 1))];

  return (
    <>
      {showGate ? <Gate onEnter={() => setShowGate(false)}/> : null}

      <div className="app" style={{ '--prose-w': `${tweaks.proseWidth}px`, '--prose-size': `${tweaks.fontSize}px` }}>
        {/* Top bar */}
        <header className="topbar" data-screen-label="top">
          <div className="tb-left">
            <button className="icon-btn" onClick={() => setRailCollapsed(!railCollapsed)} aria-label="Toggle archive">
              <Icon.Menu size={18}/>
            </button>
            <div className="tb-brand">
              <img className="tb-shield tb-shield--light" src="assets/logo-shield-light.png" alt=""/>
              <img className="tb-shield tb-shield--dark" src="assets/logo-shield-dark.png" alt=""/>
              <div className="tb-word">Oracle <span className="em">Keep</span></div>
            </div>
            <div className="tb-divider"/>
            <div className="tb-thread">
              {tweaks.lanternFlicker ? <span className="tb-lantern"/> : null}
              <span>A single, long consultation · since 14 Nov 2025</span>
            </div>
          </div>
          <div className="tb-right">
            <button className="icon-btn" onClick={newSession} aria-label="New consultation" title="New consultation"><Icon.Plus size={18}/></button>
            <button className="icon-btn" onClick={toggleTheme} aria-label="Toggle theme" title={theme === 'dark' ? 'Light the lanterns' : 'Dim the lanterns'}>
              {theme === 'dark' ? <Icon.Sun size={18}/> : <Icon.Moon size={18}/>}
            </button>
          </div>
        </header>

        {/* Rail */}
        <Rail
          collapsed={railCollapsed}
          onToggle={() => setRailCollapsed(!railCollapsed)}
          archives={archives}
          activeArchive={activeArchive}
          onSelectArchive={setActiveArchive}
          persona={persona}
          onOpenPersona={() => setPersonaMenuOpen(!personaMenuOpen)}
        />

        {/* Persona menu — anchored to the rail foot, floats above */}
        {personaMenuOpen ? (
          <>
            <div
              onClick={() => setPersonaMenuOpen(false)}
              style={{ position: 'fixed', inset: 0, zIndex: 29 }}
              aria-hidden="true"
            />
            <div
              className="menu"
              style={{
                position: 'fixed',
                left: railCollapsed ? 76 : 16,
                bottom: 76,
                top: 'auto',
                width: 300,
              }}
            >
              <div style={{ padding: '6px 10px', fontFamily: 'var(--font-display)', fontSize: 10, letterSpacing: '.16em', color: 'var(--fg-3)', textTransform: 'uppercase' }}>
                Choose an oracle
              </div>
              {PERSONAS.map(p => (
                <div
                  key={p.id}
                  className={`menu-item ${p.id === persona ? 'is-selected' : ''}`}
                  onClick={() => selectPersona(p.id)}
                >
                  <span className={`persona-avatar ${p.id}`}>{p.avatar}</span>
                  <div className="menu-item-body">
                    <div className="menu-item-title">{p.name}</div>
                    <div className="menu-item-sub">{p.tagline}</div>
                  </div>
                  {p.id === persona ? <Icon.Lantern size={14} style={{ color: 'var(--ember-500)', marginTop: 2 }}/> : null}
                </div>
              ))}
            </div>
          </>
        ) : null}

        {/* Stage */}
        <main className="stage">
          {tweaks.ribbon ? (
            <Ribbon items={items} liveIdx={streamingIdx} onJump={jumpTo}/>
          ) : <div/>}

          <div className="convo-wrap">
            {showResume && tweaks.showResume ? (
              <div className="resume-banner">
                <Icon.Lantern size={16} className="lantern-icon"/>
                <span>Welcome back. Your consultation resumed where you left off — {items.length} turns kept, four scrolls in the archive.</span>
                <button onClick={() => setShowResume(false)}>Dismiss</button>
              </div>
            ) : null}

            <div className="convo-scroll" ref={convoRef}>
              <div className="convo" style={{ maxWidth: `${tweaks.proseWidth}px`, gap: `${gap}px`, fontSize: `${tweaks.fontSize}px` }}>
                {items.length === 0 ? <EmptyState onPick={onSuggestion}/> : null}

                {items.map((it, idx) => (
                  <div key={it.id} data-item-idx={idx}>
                    {it.kind === 'archive' ? <ArchiveCard item={it}/> :
                      it.kind === 'user' ? <UserMessage item={it} you="Wren"/> :
                      it.kind === 'oracle' ? (
                        <OracleMessage
                          item={idx === streamingIdx ? { ...it, text: pendingText } : it}
                          streaming={idx === streamingIdx}
                        />
                      ) : null}
                  </div>
                ))}

                <div style={{ display: 'flex', justifyContent: 'center', color: 'var(--ink-600)', opacity: .35, marginTop: 8 }} aria-hidden="true">
                  <Flourish/>
                </div>
              </div>
            </div>

            <Composer
              onSend={sendMessage}
              disabled={pending}
              persona={personaObj.name}
              tools={activeTools}
              onToggleTool={onToggleTool}
              suggestion={suggestion}
            />
          </div>
        </main>

        {/* Tweaks */}
        <TweaksPanel title="Tweaks">
          <TweakSection label="Surface">
            <TweakColor
              label="Accent (ember)"
              value={tweaks.accent}
              options={['#C56A1F', '#9C2B1B', '#2F6E66', '#2E4A78']}
              onChange={v => setTweaks('accent', v)}
            />
            <TweakRadio
              label="Theme"
              value={theme}
              options={[{ value: 'light', label: 'Day' }, { value: 'dark', label: 'Night' }]}
              onChange={v => setTheme(v)}
            />
          </TweakSection>
          <TweakSection label="Reading">
            <TweakSlider
              label="Density"
              min={1} max={10} step={1}
              value={tweaks.density}
              onChange={v => setTweaks('density', v)}
            />
            <TweakSlider
              label="Prose width"
              min={560} max={920} step={20}
              value={tweaks.proseWidth}
              onChange={v => setTweaks('proseWidth', v)}
            />
            <TweakSlider
              label="Font size"
              min={14} max={20} step={1}
              value={tweaks.fontSize}
              onChange={v => setTweaks('fontSize', v)}
            />
          </TweakSection>
          <TweakSection label="Chrome">
            <TweakToggle
              label="Memory ribbon"
              value={tweaks.ribbon}
              onChange={v => setTweaks('ribbon', v)}
            />
            <TweakToggle
              label="Lantern flicker"
              value={tweaks.lanternFlicker}
              onChange={v => setTweaks('lanternFlicker', v)}
            />
            <TweakToggle
              label="Resume banner"
              value={tweaks.showResume}
              onChange={v => setTweaks('showResume', v)}
            />
          </TweakSection>
          <TweakSection label="The Archivist">
            <TweakSlider
              label="Compaction threshold (turns)"
              min={4} max={32} step={2}
              value={tweaks.compactionThreshold}
              onChange={v => setTweaks('compactionThreshold', v)}
            />
            <div style={{ fontFamily: 'var(--font-serif)', fontSize: 11, fontStyle: 'italic', color: 'var(--fg-3)', marginTop: -4 }}>
              How many turns the archivist keeps before condensing.
            </div>
          </TweakSection>
        </TweaksPanel>
      </div>
    </>
  );
}

// ─── Empty state ─────────────────────────────────────────────────
function EmptyState({ onPick }) {
  const SUGG = [
    { eyebrow: 'Search', text: "What's been written about the Pilot FA in 2026?" },
    { eyebrow: 'Compose', text: "Help me draft a short note to the printer about the binding." },
    { eyebrow: 'Compute', text: "Spin up a table of nib comparisons in five rows." },
    { eyebrow: 'Recall',  text: "What did we decide about the bookshelf measurements?" },
  ];
  return (
    <div className="empty">
      <img className="empty-shield" src="assets/logo-shield-light.png" alt=""/>
      <h2 className="empty-title">A new page.</h2>
      <p className="empty-lede">The Oracle is here. Begin where you left off, or set out on something new — the Keep keeps the rest.</p>
      <div className="suggestions">
        {SUGG.map((s, i) => (
          <button key={i} className="suggestion" onClick={() => onPick(s.text)}>
            <span className="suggestion-eyebrow">{s.eyebrow}</span>
            {s.text}
          </button>
        ))}
      </div>
    </div>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App/>);
